updated noobaa deps and images
Signed-off-by: Danny Zaken <dannyzaken@gmail.com>

diff --git a/metrics/Dockerfile.devel b/metrics/Dockerfile.devel
--- a/metrics/Dockerfile.devel
+++ b/metrics/Dockerfile.devel
@@ -9,7 +9,7 @@ FROM quay.io/ceph/ceph:v18
 
 ARG GOROOT=/usr/local/go
 ARG GOARCH
-ARG GOLANG_VERSION=1.26.0
+ARG GOLANG_VERSION=1.26.3
 
 ENV GOPATH=/go \
     GOROOT=${GOROOT} \
@@ -17,10 +17,10 @@ ENV GOPATH=/go \
     PATH="${GOROOT}/bin:${GOPATH}/bin:${PATH}"
 
 RUN ( test -n "${GOARCH}" && exit 0; \
-      echo -e "\n\nMissing GOARCH argument, run: make containerized-metrics-build GOARCH=amd64\n\n"; exit 1 ) \
+    echo -e "\n\nMissing GOARCH argument, run: make containerized-metrics-build GOARCH=amd64\n\n"; exit 1 ) \
     && mkdir -p ${GOROOT} \
     && curl -fsSL https://dl.google.com/go/go${GOLANG_VERSION}.linux-${GOARCH}.tar.gz \
-       | tar xzf - -C ${GOROOT} --strip-components=1
+    | tar xzf - -C ${GOROOT} --strip-components=1
 
 # TODO: remove the following cmd, when issues
 # https://github.com/ceph/ceph-container/issues/2034
